title: Refactor.Inc
email: andonov.atanas98@gmail.com
description: Recreate in my own way!
destination: docs
baseurl: "/css-advanced"
url: ""
twitter_username: naskou
facebook_username: https://www.facebook.com/profile.php?id=100008484766616
github_username: https://github.com/naskou
wesaturate_username: https://www.wesaturate.com/naskou

font-awesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.css

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal